services:
  station:
    build:
      context: .
    image: maxymchyncha/train-station-api:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations && 
             python manage.py migrate &&
             python manage.py loaddata train_station_db_data.json &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - my_db:$PGDATA

volumes:
  my_db:
