# Generated by Django 5.0.3 on 2024-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['source']},
        ),
        migrations.AddField(
            model_name='trip',
            name='crew',
            field=models.ManyToManyField(related_name='trips', to='station.crew'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
