# Generated by Django 5.0.3 on 2024-03-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_route_options_trip_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='position',
            field=models.CharField(choices=[('train_driver', 'Train driver'), ('ticket_inspector', 'Ticket inspector'), ('train_dispatcher', 'Train dispatcher'), ('security_guard', 'Security Guard'), ('cleaning_staff', 'Cleaning Staff'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
