# Generated by Django 5.0.3 on 2024-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_crew_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traintype',
            options={'verbose_name_plural': 'Train Types'},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='crew',
            name='position',
            field=models.CharField(choices=[('train_driver', 'Train driver'), ('ticket_inspector', 'Ticket inspector'), ('train_dispatcher', 'Train dispatcher'), ('security_guard', 'Security Guard'), ('cleaning_staff', 'Cleaning Staff'), ('other', 'Other')], default='other', max_length=63),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('source', 'destination'), name='unique_source_destination'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('trip', 'cargo', 'seat'), name='unique_trip_cargo_seat'),
        ),
    ]
